var config = require('./config')

const mysql = require('promise-mysql');

module.exports.init = async (configs) => {

    return mysql.createPool({
      host: config.DB.DB_SERVER,
      user: config.DB.DB_USER,
      port: config.DB.DB_PORT,
      password: config.DB.DB_PASS,
      database: config.DB.DB_NAME,
      connectionLimit: config.DB.POOL_CONNECTION_LIMIT,
    });
};


// -- MySQL Script generated by MySQL Workbench
// -- Sat Jan 11 14:12:53 2020
// -- Model: New Model    Version: 1.0
// -- MySQL Workbench Forward Engineering

// SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
// SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
// SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

// -- -----------------------------------------------------
// -- Schema store
// -- -----------------------------------------------------

// -- -----------------------------------------------------
// -- Schema store
// -- -----------------------------------------------------
// CREATE SCHEMA IF NOT EXISTS `store` DEFAULT CHARACTER SET utf8 ;
// USE `store` ;

// -- -----------------------------------------------------
// -- Table `store`.`users`
// -- -----------------------------------------------------
// CREATE TABLE IF NOT EXISTS `store`.`users` (
//   `id` INT NOT NULL,
//   `firstName` VARCHAR(45) NULL,
//   `surname` VARCHAR(45) NULL,
//   `city` VARCHAR(45) NULL,
//   `street` VARCHAR(45) NULL,
//   `email` VARCHAR(45) NULL,
//   `password` VARCHAR(100) NULL,
//   `type` VARCHAR(45) NULL,
//   PRIMARY KEY (`id`),
//   UNIQUE INDEX `email_UNIQUE` (`email` ASC))
// ENGINE = InnoDB;


// -- -----------------------------------------------------
// -- Table `store`.`categories`
// -- -----------------------------------------------------
// CREATE TABLE IF NOT EXISTS `store`.`categories` (
//   `id` INT NOT NULL AUTO_INCREMENT,
//   `name` VARCHAR(45) NULL,
//   PRIMARY KEY (`id`))
// ENGINE = InnoDB;


// -- -----------------------------------------------------
// -- Table `store`.`products`
// -- -----------------------------------------------------
// CREATE TABLE IF NOT EXISTS `store`.`products` (
//   `id` INT NOT NULL AUTO_INCREMENT,
//   `name` VARCHAR(45) NULL,
//   `price` FLOAT NULL,
//   `image` VARCHAR(300) NULL,
//   `categories_id` INT NOT NULL,
//   PRIMARY KEY (`id`),
//   INDEX `fk_products_categories1_idx` (`categories_id` ASC),
//   CONSTRAINT `fk_products_categories1`
//     FOREIGN KEY (`categories_id`)
//     REFERENCES `store`.`categories` (`id`)
//     ON DELETE NO ACTION
//     ON UPDATE NO ACTION)
// ENGINE = InnoDB;


// -- -----------------------------------------------------
// -- Table `store`.`carts`
// -- -----------------------------------------------------
// CREATE TABLE IF NOT EXISTS `store`.`carts` (
//   `id` INT NOT NULL AUTO_INCREMENT,
//   `creationDate` DATE NULL,
//   `status` VARCHAR(45) NULL,
//   `users_id` INT NOT NULL,
//   PRIMARY KEY (`id`),
//   INDEX `fk_carts_users1_idx` (`users_id` ASC),
//   CONSTRAINT `fk_carts_users1`
//     FOREIGN KEY (`users_id`)
//     REFERENCES `store`.`users` (`id`)
//     ON DELETE NO ACTION
//     ON UPDATE NO ACTION)
// ENGINE = InnoDB;


// -- -----------------------------------------------------
// -- Table `store`.`orders`
// -- -----------------------------------------------------
// CREATE TABLE IF NOT EXISTS `store`.`orders` (
//   `id` INT NOT NULL AUTO_INCREMENT,
//   `price` VARCHAR(45) NULL,
//   `city` VARCHAR(45) NULL,
//   `street` VARCHAR(45) NULL,
//   `deliveryDate` DATE NULL,
//   `date` DATE NULL,
//   `creditCardNumber` VARCHAR(4) NULL,
//   `users_id` INT NOT NULL,
//   `carts_id` INT NOT NULL,
//   PRIMARY KEY (`id`),
//   INDEX `fk_orders_users1_idx` (`users_id` ASC),
//   INDEX `fk_orders_carts1_idx` (`carts_id` ASC),
//   CONSTRAINT `fk_orders_users1`
//     FOREIGN KEY (`users_id`)
//     REFERENCES `store`.`users` (`id`)
//     ON DELETE NO ACTION
//     ON UPDATE NO ACTION,
//   CONSTRAINT `fk_orders_carts1`
//     FOREIGN KEY (`carts_id`)
//     REFERENCES `store`.`carts` (`id`)
//     ON DELETE NO ACTION
//     ON UPDATE NO ACTION)
// ENGINE = InnoDB;


// -- -----------------------------------------------------
// -- Table `store`.`items`
// -- -----------------------------------------------------
// CREATE TABLE IF NOT EXISTS `store`.`items` (
//   `id` INT NOT NULL AUTO_INCREMENT,
//   `amount` INT NOT NULL,
//   `price` FLOAT NOT NULL,
//   `carts_id` INT NOT NULL,
//   `products_id` INT NOT NULL,
//   PRIMARY KEY (`id`),
//   INDEX `fk_items_carts1_idx` (`carts_id` ASC),
//   INDEX `fk_items_products1_idx` (`products_id` ASC),
//   CONSTRAINT `fk_items_carts1`
//     FOREIGN KEY (`carts_id`)
//     REFERENCES `store`.`carts` (`id`)
//     ON DELETE NO ACTION
//     ON UPDATE NO ACTION,
//   CONSTRAINT `fk_items_products1`
//     FOREIGN KEY (`products_id`)
//     REFERENCES `store`.`products` (`id`)
//     ON DELETE NO ACTION
//     ON UPDATE NO ACTION)
// ENGINE = InnoDB;


// SET SQL_MODE=@OLD_SQL_MODE;
// SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
// SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




// grant all privileges on `store`.`*` to 'storeAdmin'@'%';